### ISSUE TITLE
Request: Google Source Repository support

### ISSUE THREAD

**Issue by Talador12** [machine-learning-apps/gke-argo#2]
This tool looks fantastic but not every repo is running GitHub. Are these input parameters agnostic to where you host git?  Or are they pre-configured for the GitHub access pattern?

**Comment by hamelsmu** [comment]
This is a GitHub Action, this is a GitHub integration specifically.

**Comment by Talador12** [comment]
Google Source Repositories are a GitHub integration? The purpose of this ticket was to address github-less solutions using GCP only
